---
title: "1960new"
author: "Henry Austin"
date: "4/26/2020"
output: html_document
---

```{r setup, include=FALSE}


tracts1960 <- readRDS("ms_6/1960MedianFamilyIncome_CensusTracts.RDS")

View(tracts1960)

library(leaflet)
library(spdplyr)
library(rmapshaper)
library(sf)
```


```{r}

data1960<- tracts1960 %>%
          filter(STATE == "Michigan" )%>%
          select(GISJOIN, MedianIncome)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tract1960 <-sf::st_read(dsn = "nhgis0002_shapefile_tl2008_us_tract_1960",
                 layer = "US_tract_1960_conflated")

# Select Michigan observations only using NHGISST variable
# NHGISST should be consistent between census years, but you might need to double-check this
# if you try 1960, 1970.
# The code is 260 for Michigan because Michigan's FIPS code is 260. Google
# Michigan FIPS code for more information.
# Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate'
# join the data1950 data with the MedianHHIncome variable by 'GISJOIN'
# so that the tract lines and income data are in one object

tract1960<-
  tract1960 %>% 
  merge(data1960, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tract1960<-sf::st_transform(tract1960,  crs="+init=epsg:4326")

saveRDS(tract1960, file="tracts1960.RDS")
# Condense size of data for faster processing

# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tract1960) %>%
  addTiles() %>%
  addPolygons(popup = paste0("Median Family Income: $", tract1960$MedianIncome), stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianIncome)) %>%
  addLegend(pal = pal, values = ~MedianIncome, opacity = 1.0)


```

