---
title: '1980'
author: "Henry Austin"
date: "4/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(leaflet)
library(spdplyr)
library(rmapshaper)
library(sf)
```


```{r}
# INcome in 1950 as a predictor
# Urban vs rural inequality, population vs inequality
# Education (are urban areas more unequal)
# Nhgis by school district 
# public vs private school inequality, unified school district and median income, educational attainment


# Import Census Tract Data

# Consult nhgis0013_ds82_1950_tract_codebook.txt codebook file to determine that
# column B0F001 contains Median Income in 1949. Rename this MedianHHIncome for clarity.
# Will need to figure out what the income variables are called
# for each new year of data you download from the codebook that comes with
# each NHGIS download.
# Select only MedianHHIncome and GISJOIN variables. GISJOIN is the variable that
# allows you to join the census tract median income data with the shapefile data.
# Also drop census tracts which reported 0 median income

data1980<- read.csv("nhgis0004_ds107_1980_tract.csv") %>%
          filter(STATE == "Michigan" & DIE001 > 0)%>%
          mutate(MedianHHIncome1980 = DIE001)%>%
          select(GISJOIN,MedianHHIncome1980)

# Import Census Tract Shapefile into R as SpatialPolygonsDataFrameFormat (SP Dataframe)
# dsn is location of folder which contains shapefiles, (.proj, .shp etc.)
# layer is the filename of the .shp file inside the
# folder dsn points to. 

tracts1980 <-sf::st_read(dsn = "nhgis0004_shapefile_tl2008_us_tract_1980",
                 layer = "US_tract_1980_conflated")

# Select Michigan observations only using NHGISST variable
# NHGISST should be consistent between census years, but you might need to double-check this
# if you try 1960, 1970.
# The code is 260 for Michigan because Michigan's FIPS code is 260. Google
# Michigan FIPS code for more information.
# Need to have spdplyr package loaded to use tidyverse commands on
# SpatialPolygonsDataFrame aka `filter' and 'mutate'
# join the data1950 data with the MedianHHIncome variable by 'GISJOIN'
# so that the tract lines and income data are in one object

tracts1980<-
  tracts1980 %>% filter(NHGISST == "260")%>%
  merge(data1980, "GISJOIN")


# Set projection of tracts dataset to `projection` required by leaflet

tracts1980<-sf::st_transform(tracts1980,  crs="+init=epsg:4326")

saveRDS(tracts1980, file="tracts1980.RDS")

# Condense size of data for faster processing

# Set palette color

pal <- colorNumeric("viridis", NULL)

#  Plot the data

leaflet(tracts1980) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(MedianHHIncome1980)) %>%
  addLegend(pal = pal, values = ~MedianHHIncome1980, opacity = 1.0)


```